version: '2'
services:
  websocket:
    build: src_py
    ports:
      - "5000:5000"
    volumes:
      - ./src_py/:/code
  static_cnt:
    build: static
    ports:
      - "8080:80"
    volumes:
      - ./static/:/usr/share/nginx/html